### ISSUE TITLE
Account name must be set up or recipe has just "Submitted by"

### ISSUE THREAD

**Issue by jfnixon** [agdavid/allergy-free-meals-rails-application#1]
A tiny suggestion: if the account name is empty, provide something, like "Anonymous Chef" or the email address, as a name just to avoid the "Submitted by" with no name.

**Comment by agdavid** [comment]
@jfnixon thank you!  I have addressed the issue with a conditional that checks if the user name is blank.  Please see the revisions [here](https://github.com/agdavid/allergy-free-meals-rails-application-heroku/commit/07d748eaf93bd3adb8cbfe5414dfadf919332611) and on the live app [here](https://allergyfreemeals.herokuapp.com/). Please do not hesitate to contact me with any further comments.
